export const StatutConventionnement = {
  CONVENTIONNEMENT_EN_COURS: 'CONVENTIONNEMENT_EN_COURS',
  CONVENTIONNEMENT_VALIDÉ: 'CONVENTIONNEMENT_VALIDÉ',
  RECONVENTIONNEMENT_INITIÉ: 'RECONVENTIONNEMENT_INITIÉ',
  RECONVENTIONNEMENT_EN_COURS: 'RECONVENTIONNEMENT_EN_COURS',
  RECONVENTIONNEMENT_VALIDÉ: 'RECONVENTIONNEMENT_VALIDÉ',
  RECONVENTIONNEMENT_REFUSÉ: 'RECONVENTIONNEMENT_REFUSÉ',
  NON_INTERESSÉ: 'NON_INTERESSÉ',
};

export const StatutCoselec = {
  POSITIF: 'POSITIF',
  NÉGATIF: 'NÉGATIF',
};

export const PhaseConventionnement = {
  PHASE_1: '1',
  PHASE_2: '2',
};
