name: Déploiement en recette

on:
  workflow_dispatch:
  push:
    branches: [recette]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - name: Retrieve cached dependencies
        id: retrieve-dependencies
        uses: actions/cache@v4
        with:
          key: node_modules-${{ hashFiles('package-lock.json') }}
          path: node_modules
      - name: Install dependencies
        if: steps.retrieve-dependencies.outputs.cache-hit == false
        run: npm ci --include=dev
      - name: Cache dependencies if not present
        if: steps.retrieve-dependencies.outputs.cache-hit == false
        uses: actions/cache@v4
        with:
          key: node_modules.-${{ hashFiles('package-lock.json') }}
          path: node_modules
      - name: Copy robots.txt
        uses: canastro/copy-file-action@master
        with:
          source: desindexation/robots.txt
          target: public/robots.txt
      - name: Build application
        run: npm run build
      - name: Copy .htaccess
        uses: canastro/copy-file-action@master
        with:
          source: .htaccess
          target: dist/.htaccess
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PILOTAGE_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
        with:
          environment: recette
          ignore_missing: true
          ignore_empty: true
